export const cart = {image:"/assets/cart.svg",name:'cart logo'}
export const SEARCH = {image:"/assets/search.svg",name:'search logo'}
export const SEARCH_BLACK = {image:"/assets/search-black.svg",name:'search logo'}
export const SEARCH_WITH_NO_BORDER = {image:"/assets/search-without-border.svg",name:'search logo'}
export const HEART = {image:"/assets/heart.svg",name:'heart'}
export const HEART_FILLED = {image:"/assets/heart-filled.svg",name:'filled heard'}
export const VERIFIED = {image:"/assets/verified.svg",name:'verified logo'}
export const STAR = {image:"/assets/star.svg",name:'star logo'}
export const WHY_US = {image:"/assets/Why-us.jpeg",name:"Why us"}
export const READ_MORE = {image:"/assets/read-more-arrow.svg",name:"readmore"}
export const CONTACT = {image:"/assets/contact.svg",name:"Contact"}
export const MAIL = {image:"/assets/mail.svg",name:"mail"}
export const HAMBURGER = {image:"/assets/hamburger.svg",name:"hamburger"}
export const MOVE_TO_TOP = {image:"public/assets/move-top.svg",name:"move to top"}
export const DROPDOWN = {image:"/assets/dropdown-more.svg",name:"dropdown"}
export const CROSS = {image:"/assets/cross.svg",name:"cross"}
export const BELL = {image:"/assets/bell.svg",name:"bell"}
export const NOTIFICATION_REMINDER = {image:"/assets/notification-reminder.svg",name:"notification"}
export const LOAD_MORE = {image:"/assets/load-more.svg",name:"load more"}
export const TICK = {image:"/assets/tick.svg",name:"tick "}
export const LOCATION = {image:"/assets/location.svg",name:'location'}
export const DELIVERY_MAN = {image:"/assets/deliveryMan.svg",name:'delivery'}
export const ORDER_CONFIRMED = {image:"/assets/order-confirmed.svg",name:'notification reminder'}
export const ORDER_DELIVERED = {image:"/assets/order-delivered.svg",name:'order deliver'}
export const PROTECTED = {image:"/assets/protected.svg",name:'protected'}
export const PAYPAL = { name: "paypal logo", image: "/assets/paypal.png" }
export const AMERICAN_EXPRESS = { name: "american express logo", image: "/assets/american-express.png" }
export const VISA = { name: "visa logo", image: "/assets/visa.png" }
export const G_PAY = { name: "G-pay logo", image: "/assets/g-pay.png" }
export const APPLE_PAY = { name: "apple-pay logo", image: "/assets/apple-pay.png" } 
export const NOT_FOUND = { name: "Notfound", image: "/assets/not-found.svg" } 
export const DATE = { name: "date", image: "/assets/date.svg" } 
export const PACKAGING_AND_SECURITY = { name: "packaging-and-security", image: "/assets/shipping/packaging-and-security.svg" } 
export const DELIVERY_ISSUES = { name: "delivery issues", image: "/assets/shipping/delivery-issues.svg" } 
export const ORDER_PROCESSING_TIME = { name: "ORDER PROCESSING TIME ", image: "/assets/shipping/order-processing-time.svg" } 
export const SHIPPING_FEES = { name: "SHIPPING FEES", image: "/assets/shipping/shipping-fees.svg" } 
export const ALERT = { name: "alert icon", image: "/assets/alert.svg" } 
export const UPLOAD_IMAGE = { name: "upload ", image: "/assets/upload-image.svg" } 
export const USD = {name:'USD',image:'/assets/usd.svg'}
export const EURO = {name:'euro',image:'/assets/euro.svg'}
export const CAN_USD = {name:'canaddian usd',image:'/assets/can-usd.svg'}
export const ORDER_PLACED = {name:'verified',image:'/assets/order-placed.svg'}
