export const cart = {image:"/assets/cart.svg",name:'cart logo'}
export const SEARCH = {image:"/assets/search.svg",name:'search logo'}
export const SEARCH_BLACK = {image:"/assets/search-black.svg",name:'search logo'}
export const SEARCH_WITH_NO_BORDER = {image:"/assets/search-without-border.svg",name:'search logo'}
export const HEART = {image:"/assets/heart.svg",name:'heart logo'}
export const VERIFIED = {image:"/assets/verified.svg",name:'verified logo'}
export const STAR = {image:"/assets/star.svg",name:'star logo'}
export const WHY_US = {image:"/assets/Why-us.jpeg",name:"Why us"}
export const READ_MORE = {image:"/assets/read-more-arrow.svg",name:"readmore"}
export const CONTACT = {image:"/assets/contact.svg",name:"Contact"}
export const MAIL = {image:"/assets/mail.svg",name:"mail"}
export const HAMBURGER = {image:"/assets/hamburger.svg",name:"hamburger"}
export const MOVE_TO_TOP = {image:"public/assets/move-top.svg",name:"move to top"}
export const DROPDOWN = {image:"/assets/dropdown-more.svg",name:"dropdown"}
export const CROSS = {image:"/assets/cross.svg",name:"cross"}
